name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run check-types
      - name: Run tests
        run: npm test
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Run tests
        run: npm test
